module ::PP::PPMethods
end

class ::PrettyPrint
end

class ::PP < ::PrettyPrint
  include ::PP::PPMethods
end

module ::PP::ObjectMixin
end

module ::JSON
end

module ::JSON::Ext
end

module ::JSON::Ext::Generator
end

module ::JSON::Ext::Generator::GeneratorMethods
end

module ::JSON::Ext::Generator::GeneratorMethods::Object
end

class ::Object
  include ::PP::ObjectMixin

  include ::JSON::Ext::Generator::GeneratorMethods::Object

  private def bar: () { (?::Integer a, ?::Integer b, kw: ::Integer, ?kw2: nil) [self: ::Object] -> ::Integer } -> ::Integer

  private def foo: () { (?::Integer | ::String a, ?::String | ::Regexp | ::Integer b, kw: ::Integer | ::Float, ?kw2: ::Symbol | nil) [self: ::Object] -> (::Array[::Integer | ::String | ::Symbol] | ::Array[::String | ::Regexp | ::Float | nil] | ::Integer) } -> ::Integer

  private def baz: () ?{ (?) -> untyped } -> ::Integer
end

module ::JSON::Ext::Generator::GeneratorMethods::Integer
end

module ::Comparable
end

class ::Numeric
  include ::Comparable
end

class ::Integer < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Integer
end

module ::JSON::Ext::Generator::GeneratorMethods::String
end

module ::JSON::Ext::Generator::GeneratorMethods::String::Extend
end

class ::String
  extend ::JSON::Ext::Generator::GeneratorMethods::String::Extend

  include ::JSON::Ext::Generator::GeneratorMethods::String

  include ::Comparable
end

class ::Symbol
  include ::Comparable
end

module ::JSON::Ext::Generator::GeneratorMethods::Array
end

module ::Enumerable[unchecked out Elem]
end

class ::Array[unchecked out Elem]
  include ::JSON::Ext::Generator::GeneratorMethods::Array

  include ::Enumerable[untyped]
end

class ::Regexp
end

module ::JSON::Ext::Generator::GeneratorMethods::Float
end

class ::Float < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Float
end

module ::JSON::Ext::Generator::GeneratorMethods::NilClass
end

class ::NilClass
  include ::JSON::Ext::Generator::GeneratorMethods::NilClass
end

class ::Foo
  def self.foo: () { () [self: singleton(::Foo)] -> nil } -> nil
end
