class ::Racer::Agent
  def foo: (::RBSCollectorTest::A::B::C::D a) -> ::RBSCollectorTest::A::B::C::E
end

module ::Racer
end

module ::RBSCollectorTest::A::B::C::E
end

module ::RBSCollectorTest::A::B::C
end

class ::RBSCollectorTest::A::B
end

module ::RBSCollectorTest::A
end

class ::RBSCollectorTest
end

class ::RBSCollectorTest::A::B::C::D
end
