class ::FalseClass
end

class ::TrueClass
end

class ::NilClass
end

class ::RBSCollectorTest
  def foo: (bool a, bool b, nil c) -> bool

  def bar: () -> bool

  def baz: () -> nil

  def union: () -> (nil | bool)
end
