class ::Integer
  def prime?: () -> nil

  def +: () -> nil
       | ...

  def self.bar: () -> nil

  def self.sqrt: () -> nil
               | ...
end

class ::Hash[unchecked out K, unchecked out V]
  def foo: () -> nil

  private def initialize: () -> void
                        | ...
end
