class ::RBSCollectorTest
  def foo: (::Array[::String | ::Array[::Integer | ::String]] a, *::RBSCollectorTest::A::B::C::D | ::RBSCollectorTest::A::B::C::E args, ::Hash[::Symbol | ::String, ::Float | ::Regexp] b, **::RBSCollectorTest::A::B::C::D | ::RBSCollectorTest::A::B::C::E options) -> ::Hash[::Symbol | ::RBSCollectorTest::A::B | ::Hash[::Array[::Integer], ::Integer | ::Symbol], ::String]
end

class ::RBSCollectorTest::A::B
end

module ::RBSCollectorTest::A
end

class ::RBSCollectorTest::A::B::C::D
end

module ::RBSCollectorTest::A::B::C
end

module ::RBSCollectorTest::A::B::C::E
end
