class ::RBSCollectorTest::A::B
  def foo: (::String a) -> ::Integer
end

class ::RBSCollectorTest
end

module ::RBSCollectorTest::A
end

class ::Array[unchecked out Elem]
  include ::RBSCollectorTest::A

  def to_json: () -> nil
             | ...
end

class ::NilClass
end
