class ::Array[unchecked out Elem]
end

class ::Hash[unchecked out K, unchecked out V]
end

class ::RBSCollectorTest
  def foo: (nil a, ?nil b, *untyped args, c: nil, ?d: nil, **untyped options) ?{ (?) -> untyped } -> nil

  def bar: (*untyped, **untyped) -> nil

  def baz: (nil a, *untyped args, nil b) -> nil

  def param_without_name: (nil) -> nil
end
