class ::RBSCollectorTest
  def foo: () -> nil
end

module ::RBSCollectorTest::A : ::BasicObject
end

class ::RBSCollectorTest::A::B
end

module ::RBSCollectorTest::A::B::C
end

class ::RBSCollectorTest::A::B::C::D < ::RBSCollectorTest::A::B
  extend ::RBSCollectorTest::A

  prepend ::RBSCollectorTest::A::B::C::E

  include ::RBSCollectorTest::A

  include ::RBSCollectorTest::A::B::C
end

module ::RBSCollectorTest::A::B::C::E
  extend ::RBSCollectorTest::A::B::C

  prepend ::RBSCollectorTest::A::B::C

  include ::RBSCollectorTest::A
end

class ::RBSCollectorTest::A::B::C::F
end

module ::Enumerable[unchecked out Elem] : ::BasicObject
end

class ::Array[unchecked out Elem]
end

module ::Racer
end

class ::Racer::Agent < ::Array[untyped]
end

class ::Object
  include ::RBSCollectorTest::A

  include ::Enumerable[untyped]

  def each: () { (untyped) -> untyped } -> untyped
end

module ::Delegator1234
end

class ::Tempfile < ::File
end
